---
- name: Apache server installed
  hosts: web
  gather_facts: no
  become: yes

  tasks:
  - name: latest apache version installed
    package:
      name: apache2
      state: latest
    
  - name: Apached enabled and running
    service:
      name: apache2
      enabled: yes
      state: started
  - name: copy index.html
    copy:
      src: ~/mycode/files/index.html
      dest: /var/www/html/

  - name: Download a copy of apache2.conf
    get_url:
      url: https://raw.githubusercontent.com/rzfeeser/alta3files/master/apache2.conf
      dest: /etc/apache2/
    notify:
      - restart_apache

  - name: MYSQL (Maria DB) is running
    service:
      name: mariadb
      enabled: yes
      state: started

  - name: Modify SQL conf file to listen on all interfaces
    lineinfile:
      dest: /etc/mysql/my.cnf
      regexp: "^bind-address"
      line: "bind-address=0.0.0.0"
    notify:
      restart-mysql

  handlers:
  - name: restart_apache
    service:
      name: apache2
      state: restarted
    listen: restart_webservices
      
  - name: restart_mysql
    service:
      name: mariadb
      state: restarted
    listen: restart_webservices
